### ISSUE TITLE
Node and term steps fail

### ISSUE THREAD

**Issue by ataylorme** [drush-ops/behat-drush-endpoint#16]
See https://github.com/pantheon-systems/example-drops-8-composer/pull/255 for more background. 

Here is an example of a [failing build](https://circleci.com/gh/pantheon-systems/example-drops-8-composer/3076) with:

- `drupal/drupal-driver` `v1.4.0`
- `drupal/drupal-extension` `v3.4.1`
- `drush-ops/behat-drush-endpoint` `9.3.0`
- Headless Chrome
- Drush Driver
- node creation and taxonomy term steps failing
- User creations steps working

**Comment by greg-1-anderson** [comment]
The cause here was that the `behat` command was not installed on the site.
