### ISSUE TITLE
Make it compatible with Drush 11

### ISSUE THREAD

**Issue by jurgenhaas** [drush-ops/behat-drush-endpoint#30]
Wanted to test Drush 11 in our development environment but it fails, because we have drush-ops/behat-drush-endpoint in all our projects too and that has a version conflict with Drush 11.

Is it just the dependency that needs updating or any other code too?

**Comment by greg-1-anderson** [comment]
What error are you getting? Didn't try it, but I didn't notice a restriction in this project or drupal/drupal-driver that should be a problem.

**Comment by ptmkenny** [comment]
@greg-1-anderson  In my case, the error is a simple requirements error.

**composer.json**

```
"drush/drush": "^11",
"drush-ops/behat-drush-endpoint": "^9.4",
```

Error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - drush-ops/behat-drush-endpoint 9.4.0 conflicts with drush/drush 11.0.4.
    - drush-ops/behat-drush-endpoint 9.4.0 conflicts with drush/drush 11.0.3.
    - drush-ops/behat-drush-endpoint 9.4.0 conflicts with drush/drush 11.0.2.
    - drush-ops/behat-drush-endpoint 9.4.0 conflicts with drush/drush 11.0.1.
    - drush-ops/behat-drush-endpoint 9.4.0 conflicts with drush/drush 11.0.0.
    - drush-ops/behat-drush-endpoint 9.4.0 conflicts with drush/drush 11.0.0-rc7.
    - drush-ops/behat-drush-endpoint 9.4.0 conflicts with drush/drush 11.0.0-rc6.
    - drush-ops/behat-drush-endpoint 9.4.0 conflicts with drush/drush 11.0.0-rc5.
    - drush-ops/behat-drush-endpoint 9.4.0 conflicts with drush/drush 11.0.0-rc4.
    - drush-ops/behat-drush-endpoint 9.4.0 conflicts with drush/drush 11.0.0-rc3.
    - drush-ops/behat-drush-endpoint 9.4.0 conflicts with drush/drush 11.0.0-rc2.
    - drush-ops/behat-drush-endpoint 9.4.0 conflicts with drush/drush 11.0.0-rc1.
    - Root composer.json requires drush-ops/behat-drush-endpoint ^9.4 -> satisfiable by drush-ops/behat-drush-endpoint[9.4.0].
    - Root composer.json requires drush/drush ^11 -> satisfiable by drush/drush[11.0.0-rc1, ..., 11.0.4].
``

**Comment by greg-1-anderson** [comment]
Oh, I overlooked the explicit conflict:

https://github.com/drush-ops/behat-drush-endpoint/blob/9.x/composer.json#L32

It will probably work with that removed / updated.

**Comment by ptmkenny** [comment]
@greg-1-anderson Yes, I just forked the repo, removed the block, and tested in lando + GitHub Actions.  My behat tests are working the same as before run through this + drush 11.  Pull request here: https://github.com/drush-ops/behat-drush-endpoint/pull/31

**Comment by jurgenhaas** [comment]
Works great, thanks a lot.
