### ISSUE TITLE
timezone settings issue

### ISSUE THREAD

**Issue by rubelyn** [drush-ops/behat-drush-endpoint#5]
Customer is getting a strtotime() warning that causes test to fail.

Here is the error:

`Warning: strtotime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /opt/drupalextension/vendor/guzzlehttp/guzzle/src/Cookie/SetCookie.php line 225`

Existing issue on Drupal.org - https://www.drupal.org/node/2671220

Original Ticket:
https://pantheon-systems.desk.com/agent/case/58722

@greg-1-anderson

**Comment by greg-1-anderson** [comment]
Sorry I did not see this report back in April.

The above warning will appear whenever date.timezone is not set. This is a general PHP issue unrelated to this library. The solution is to set date.timezone as the warning message advises.
