### ISSUE TITLE
Plans for Drush 9

### ISSUE THREAD

**Issue by jhedstrom** [drush-ops/behat-drush-endpoint#7]
I'm working on testing the Drupal Behat Extension with Drush 9, and the build fails during the behat drush endpoint testing.

Wondering if there are plans to port this to Drush 9?

See https://github.com/jhedstrom/drupalextension/issues/419

**Comment by greg-1-anderson** [comment]
Yes, I intend to do this, but at this point I don't know when I will get to it.  Help appreciated.

**Comment by arosboro** [comment]
@greg-1-anderson I'm about to need this and can offer some help if you can provide direction.  I'll try to familiarize myself with this code in the meantime.

**Comment by arosboro** [comment]
@greg-1-anderson I looked into this today on a fork of this repository.

The following documentation helped, for anyone that needs to reference it:
* http://docs.drush.org/en/master/commands/
* https://weitzman.github.io/blog/port-to-drush9

With a Global command file, I'm getting errors related to dependency injection:

> [error]  \Drupal::$container is not initialized yet. \Drupal::setContainer() must be called with a real container.

I'm assuming drush.services.yml does not load for Global command files.  I've spent a bit of time troubleshooting, by both including the original Drupal 8 file to avoid rewriting much code, and also porting the `behat.d8.drush.inc` and `behat-drush-common.inc` in their entirety.  Either way, the error message is the same using each approach.

Is this a common error when writing drush 9 commands that you might know a fix for off the top of your head?  My work in progress is here: https://github.com/arosboro/behat-drush-endpoint/tree/issue-7

**Comment by greg-1-anderson** [comment]
> I'm assuming drush.services.yml does not load for Global command files.

This is correct. If you need to inject Drupal services, create a module. However, in the case of this set of commands, I think it should be fine to make a global command and just use `Drupal::...` as needed.

I'm not sure why you are getting that error message. Maybe your commands are not bootstrapping to a high enough level? The default is `full` for module commands; don't remember the default for global commands. Try adding `@bootstrap full` and see if that works better.

**Comment by arosboro** [comment]
I am unable to get behat from my local machine to connect to a remote environment on pantheon.  My guess is that it fails due to failure to allocate a PTY terminal -- so I am at a loss for what to do to establish a working behat setup.  Is this a known issue with pantheon and drush 9?  I only get the error message when I call drush directly, not when I use terminus.

**Comment by greg-1-anderson** [comment]
Drush 9 does not work on Pantheon

**Comment by arosboro** [comment]
Does this include site local drush 9, I have been having luck with the command `terminus -n drush 
 'site'.'env' -- help behat` which I'm assuming uses drush launcher to find the vendor bin.

So if Drush 9 remotely doesn't work on Pantheon, and Drush 8 is no longer compatible with Drupal 8.5.3+, is support on the roadmap?

**Comment by greg-1-anderson** [comment]
Regarding Drush, the official status of Drush 8 for Drupal 8.4+ is "happens to work". We have not had any reports of failure with Drush 8 on Drupal 8.4 or Drupal 8.5. Site-local Drush 8 should continue to work for Drupal 8.4+. Global Drush 8 mixes Symfony 2 and Symfony 3 APIs when bootstrapping Drupal, which could fail on Drupal 8.4+ at any time, e.g. if a contrib module called Symfony APIs.

This isn't really the right issue queue for Pantheon roadmap issues, but there are definitely cards related to Drush work in the backlog. There is no particular date for supporting Drush 9 on the platform. More work is needed before site-local Drush 9 will fully work, and it is not possible to select Drush 9 as your global Drush.

**Comment by arosboro** [comment]
I understand.  Thanks for the explanation.

**Comment by greg-1-anderson** [comment]
This has been merged. See https://pantheon.io/blog/drush-940-release-available-pantheon for details on using Drush 9 on Pantheon. Thanks for your work on porting.
